language: python
cache: pip

python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy"
    - "pypy3"
    - "nightly"
env:
    - DJANGO_VERSION=1.8.0
    - DJANGO_VERSION=1.9.0
    - DJANGO_VERSION=1.10.0
    - DJANGO_VERSION=1.11
matrix:
    exclude:
        # Django >= 1.9 does not support Python 3.3 (or pypy3 which is Python 3.2):
        - python: "3.2"
          env: DJANGO_VERSION=1.9.0
        - python: "3.2"
          env: DJANGO_VERSION=1.10.0
        - python: "3.2"
          env: DJANGO_VERSION=1.11
        - python: "3.3"
          env: DJANGO_VERSION=1.9.0
        - python: "3.3"
          env: DJANGO_VERSION=1.10.0
        - python: "3.3"
          env: DJANGO_VERSION=1.11
        - python: "pypy3"
          env: DJANGO_VERSION=1.9.0
        - python: "pypy3"
          env: DJANGO_VERSION=1.10.0
        - python: "pypy3"
          env: DJANGO_VERSION=1.11
install:
    - pip install -q Django~=$DJANGO_VERSION
    - python setup.py -q install
script: python manage.py test
