language: python
cache: pip

matrix:
    include:
        # Certain Django versions do not support certain Python versions
        - python: "2.7"
          env: DJANGO_VERSION=1.8.0
        - python: "2.7"
          env: DJANGO_VERSION=1.9.0
        - python: "2.7"
          env: DJANGO_VERSION=1.10.0
        - python: "2.7"
          env: DJANGO_VERSION=1.11.0
        - python: "3.2"
          env: DJANGO_VERSION=1.8.0
        - python: "3.3"
          env: DJANGO_VERSION=1.8.0
        - python: "3.4"
          env: DJANGO_VERSION=1.8.0
        - python: "3.4"
          env: DJANGO_VERSION=1.9.0
        - python: "3.4"
          env: DJANGO_VERSION=1.10.0
        - python: "3.4"
          env: DJANGO_VERSION=1.11.0
        - python: "3.4"
          env: DJANGO_VERSION=2.0.0
        - python: "3.5"
          env: DJANGO_VERSION=1.9.0
        - python: "3.5"
          env: DJANGO_VERSION=1.10.0
        - python: "3.5"
          env: DJANGO_VERSION=1.11.0
        - python: "3.5"
          env: DJANGO_VERSION=2.0.0
        - python: "3.5"
          env: DJANGO_VERSION=2.1.0
        - python: "3.6"
          env: DJANGO_VERSION=1.11.0
        - python: "3.6"
          env: DJANGO_VERSION=2.0.0
        - python: "3.6"
          env: DJANGO_VERSION=2.1.0
        - python: "3.7"
          env: DJANGO_VERSION=2.0.0
          dist: xenial
        - python: "3.7"
          env: DJANGO_VERSION=2.1.0
          dist: xenial
        - python: "nightly"
          env: DJANGO_VERSION=2.1.0
          dist: xenial
        - python: "pypy"
          env: DJANGO_VERSION=1.11.0
        - python: "pypy3"
          env: DJANGO_VERSION=1.8.0
install:
    - pip install -q Django~=$DJANGO_VERSION
    - pip install docutils pygments # needed for tests
    - python setup.py -q install
script:
    - python manage.py test
    - |
        if python -c 'import sys; sys.exit(0 if sys.version_info >= (3,4) else 1)' ; then
            python setup.py check --restructured --strict --metadata
        fi
